default_stages: [commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: detect-private-key
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
    args: [--unsafe]

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.75.0
  hooks:
  - id: terraform_fmt
    args:
    - --args=-check
    - --args=-recursive
  - id: terraform_validate
  - id: terraform_tflint
  - id: terraform_tfsec
